import { useMemo, useRef, useState } from 'react'
import { AlertTriangle, CheckCircle2, FileSpreadsheet, HelpCircle, Upload } from 'lucide-react'
import * as XLSX from 'xlsx'
import { SABESP_SHEETS, type SabespSheetData, type SabespSheetId, useSabespStore } from './sabespStore'

const norm = (v: unknown) => String(v ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().replace(/\s+/g, ' ').trim()
const scalar = (v: unknown) => v instanceof Date ? v.toISOString().slice(0, 10) : (typeof v === 'string' ? v.trim() : v as string | number | boolean | null)
function parseSheet(sheet: XLSX.WorkSheet, id: SabespSheetId): SabespSheetData | null {
  const cfg = SABESP_SHEETS.find((item) => item.id === id)!; const matrix = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: '', raw: false })
  let best = -1; let score = 0
  matrix.slice(0, 20).forEach((row, index) => { const cells = row.map(norm); const candidate = cfg.keyColumns.reduce((sum, key) => { const wanted = norm(key); return sum + (cells.some((cell) => cell === wanted || cell.startsWith(wanted)) ? 1 : 0) }, 0); if (candidate > score) { score = candidate; best = index } })
  if (best < 0 || score === 0) return null
  const headers = matrix[best].map((cell, i) => String(cell || `Coluna ${i + 1}`).trim()); const rows = matrix.slice(best + 1).map((raw) => Object.fromEntries(headers.map((header, i) => [header, scalar(raw[i])]))).filter((row) => Object.values(row).some((v) => String(v ?? '').trim()))
  const seen = new Map<string, number>(); const parsed = rows.map((values) => { const base = cfg.keyColumns.map((key) => String(values[key] ?? '')).join('|').trim() || JSON.stringify(values); const n = seen.get(base) ?? 0; seen.set(base, n + 1); return { key: `${base}#${n}`, values, active: true, importedAt: '' } })
  return { headers, rows: parsed, sourceName: cfg.sheetName }
}
type Candidate = { filename: string; sheets: Partial<Record<SabespSheetId, SabespSheetData>>; rejected: string[] }
export function SabespPanel() {
  const { sheets, imports, applyWorkbook } = useSabespStore(); const [active, setActive] = useState<SabespSheetId>('cadastro_servicos'); const [candidate, setCandidate] = useState<Candidate | null>(null); const input = useRef<HTMLInputElement>(null)
  const data = sheets[active]; const activeRows = data?.rows.filter((row) => row.active) ?? []
  const metrics = useMemo(() => ({ chamados: sheets.cadastro_servicos?.rows.filter((x) => x.active).length ?? 0, os: sheets.ordens_servico?.rows.filter((x) => x.active).length ?? 0, pendencias: sheets.ocorrencias?.rows.filter((x) => x.active && /ABERTA|PENDENTE/i.test(String(x.values.STATUS ?? ''))).length ?? 0, valor: (sheets.medicao?.rows ?? []).filter((x) => x.active).reduce((sum, x) => sum + Number(String(x.values['VALOR APROVADO'] ?? x.values.VALOR ?? 0).replace('.', '').replace(',', '.')), 0) }), [sheets])
  async function selectFile(file: File) { try { const wb = XLSX.read(await file.arrayBuffer(), { type: 'array', cellDates: true }); const found: Candidate['sheets'] = {}; const rejected: string[] = []; for (const definition of SABESP_SHEETS) { const exact = wb.Sheets[definition.sheetName] ?? Object.entries(wb.Sheets).find(([name]) => norm(name).includes(norm(definition.sheetName).replace(/^\d+[A-Z]?\.\s*/, '')))?.[1]; if (!exact) { rejected.push(`${definition.label}: aba não encontrada`); continue }; const parsed = parseSheet(exact, definition.id); if (!parsed) rejected.push(`${definition.label}: cabeçalho não reconhecido`); else found[definition.id] = parsed }; setCandidate({ filename: file.name, sheets: found, rejected }) } catch { setCandidate({ filename: file.name, sheets: {}, rejected: ['Não foi possível ler o arquivo. Use Excel, ODS ou CSV exportado.'] }) } }
  const predicted = candidate && Object.values(candidate.sheets).reduce((sum, sheet) => sum + (sheet?.rows.length ?? 0), 0)
  return <section className="min-h-0 flex-1 overflow-auto bg-[#1f1f1f] p-5 text-white"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Operacional Sabesp</h2><p className="text-sm text-[#a3a3a3]">A cópia operacional da planilha: importação, acompanhamento e fechamento do contrato.</p></div><div><input ref={input} type="file" accept=".xlsx,.xls,.ods,.csv" className="hidden" onChange={(e) => e.target.files?.[0] && void selectFile(e.target.files[0])}/><button onClick={() => input.current?.click()} className="inline-flex items-center gap-2 rounded-lg bg-[#f97316] px-4 py-2 text-sm font-semibold hover:bg-[#ea580c]"><Upload size={16}/>Importar planilha atualizada</button></div></div>
    <div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Chamados', metrics.chamados], ['OS', metrics.os], ['Ocorrências abertas', metrics.pendencias], ['Medição aprovada', metrics.valor ? `R$ ${metrics.valor.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}` : '—']].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-[#525252] bg-[#2c2c2c] p-3"><p className="text-[11px] text-[#a3a3a3]">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>)}</div>
    <div className="mb-4 flex gap-2 overflow-x-auto border-b border-[#525252] pb-2">{SABESP_SHEETS.map((item) => <button key={item.id} onClick={() => setActive(item.id)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs ${active === item.id ? 'bg-[#f97316] text-white' : 'text-[#a3a3a3] hover:bg-[#333]'}`}>{item.label}</button>)}</div>
    <div className="rounded-xl border border-[#525252] bg-[#2c2c2c]"><div className="flex items-center justify-between border-b border-[#525252] px-4 py-3"><div><h3 className="font-semibold">{SABESP_SHEETS.find((item) => item.id === active)?.label}</h3><p className="text-xs text-[#a3a3a3]">{activeRows.length} registro(s) ativo(s) importado(s)</p></div><span className="inline-flex items-center gap-1 text-xs text-[#a3a3a3]"><HelpCircle size={13}/>Dados completos da planilha</span></div><div className="max-h-[55vh] overflow-auto"><table className="min-w-full text-left text-xs"><thead className="sticky top-0 bg-[#3d3d3d] text-[#a3a3a3]"><tr>{(data?.headers ?? ['Importe a planilha para carregar esta aba']).map((header) => <th key={header} className="whitespace-nowrap px-3 py-2.5 font-medium">{header}</th>)}</tr></thead><tbody>{activeRows.map((row) => <tr key={row.key} className="border-t border-[#525252] even:bg-white/[.03]">{(data?.headers ?? []).map((header) => <td key={header} className="max-w-64 whitespace-nowrap px-3 py-2" title={String(row.values[header] ?? '')}>{String(row.values[header] ?? '—')}</td>)}</tr>)}{!activeRows.length && <tr><td className="px-4 py-12 text-center text-[#a3a3a3]">Nenhum dado importado nesta aba.</td></tr>}</tbody></table></div></div>
    {candidate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-2xl border border-[#525252] bg-[#2c2c2c] p-5 shadow-2xl"><div className="flex items-center gap-2"><FileSpreadsheet className="text-[#f97316]" size={20}/><div><h3 className="font-bold">Conferir importação</h3><p className="text-xs text-[#a3a3a3]">{candidate.filename}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="Abas reconhecidas" value={Object.keys(candidate.sheets).length}/><Stat label="Linhas lidas" value={predicted ?? 0}/><Stat label="Ausentes/recusadas" value={candidate.rejected.length}/><Stat label="Fonte" value="Planilha vence"/></div>{candidate.rejected.length > 0 && <div className="mt-4 rounded-lg border border-[#f59e0b]/40 bg-[#f59e0b]/10 p-3 text-xs text-[#fbbf24]"><AlertTriangle className="mr-1 inline" size={13}/>{candidate.rejected.join(' · ')}</div>}<p className="mt-4 text-xs text-[#a3a3a3]">Ao aplicar, registros com a mesma chave serão atualizados, entradas iguais permanecerão inalteradas e linhas ausentes serão arquivadas.</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setCandidate(null)} className="rounded-lg px-4 py-2 text-sm text-[#a3a3a3]">Cancelar</button><button onClick={() => { applyWorkbook(candidate); setCandidate(null) }} disabled={!Object.keys(candidate.sheets).length} className="inline-flex items-center gap-2 rounded-lg bg-[#22c55e] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40"><CheckCircle2 size={16}/>Aplicar atualização</button></div></div></div>}
    {imports[0] && <p className="mt-3 text-xs text-[#6b6b6b]">Última importação: {imports[0].filename} · {imports[0].created} novos · {imports[0].updated} atualizados · {imports[0].unchanged} inalterados · {imports[0].archived} arquivados.</p>}
  </section>
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border border-[#525252] bg-[#333] p-2.5"><p className="text-[10px] text-[#a3a3a3]">{label}</p><p className="mt-1 font-bold text-[#f5f5f5]">{value}</p></div> }
