import { useMemo, useRef, useState } from 'react'
import { CalendarDays, ClipboardList, FileSpreadsheet, HardHat, Package, ReceiptText, ShieldCheck, Upload, Wrench } from 'lucide-react'
import * as XLSX from 'xlsx'
import { useSabespStore, type SabespStatus } from './sabespStore'
import { calcularMedicao } from '@/features/financeiro/utils/medicao/motorDaMedicao'

const DATA_SHEETS = ['01. CONFIGURAÇÕES', '02. TABELA DE PREÇOS', '03. CADASTRO DE SERVIÇOS', '04. PROGRAMAÇÃO DIÁRIA', '05. ORDENS DE SERVIÇO', '06. APONTAMENTO DIÁRIO', '07. MATERIAIS', '08. EQUIPE', '09. MEDIÇÃO', '11. OCORRÊNCIAS']
const LATER_SHEETS = ['01A. BANCO DE CUSTOS', '01B. CARTEIRA E TICKET', '10. DIÁRIO DE OBRA', '12. FATURAMENTO', '13. RESUMO GERENCIAL', '14. DASHBOARD']
const tabs = [{ id: 'chamados', label: 'Chamados Sabesp', icon: ClipboardList }, { id: 'programacao', label: 'Programação Diária', icon: CalendarDays }, { id: 'os', label: 'Ordens de Serviço', icon: Wrench }, { id: 'apontamento', label: 'Apontamento Diário', icon: HardHat }, { id: 'materiais', label: 'Materiais', icon: Package }, { id: 'equipe', label: 'Equipe Operacional', icon: ShieldCheck }, { id: 'medicao', label: 'Medição', icon: ReceiptText }, { id: 'importar', label: 'Importar planilha', icon: FileSpreadsheet }]
const get = (row: Record<string, unknown>, names: string[]) => String(names.map((n) => row[n]).find((v) => v != null && v !== '') ?? '').trim()
const status = (raw: string): SabespStatus => /conclu/i.test(raw) ? 'concluido' : /program/i.test(raw) ? 'programado' : /execu/i.test(raw) ? 'em_execucao' : 'aberto'

export function SabespPanel() {
  const store = useSabespStore(); const [tab, setTab] = useState('chamados'); const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState('')
  const contract = store.contracts[0]
  const eligible = store.orders.filter((o) => o.status === 'concluido' && o.beforePhotos.length > 0 && o.afterPhotos.length > 0 && o.pavementRestored)
  const pendingEvidence = store.orders.filter((o) => o.status === 'concluido' && !eligible.includes(o))
  const measurement = useMemo(() => {
    // O motor canônico ainda é chamado nesta adaptação; sem preço confirmado o total fica pendente.
    const catalog = { numeroContrato: contract.name, fatorPadrao: 1, regioes: [{ codigo: contract.region, nome: contract.name }], servicos: store.prices.map((p) => ({ id: p.id, descricao: p.description, unidade: p.unit, precoZn: p.value, porRegiao: { [contract.region]: { codigo: p.key, precoOverride: p.value } }, flag: 'ok' })) } as never
    return calcularMedicao(catalog, contract.name, contract.region, store.logs.filter((l) => eligible.some((o) => o.id === l.orderId)).map((l) => ({ obra: contract.name, servicoCatalogoId: store.orders.find((o) => o.id === l.orderId)?.serviceKey ?? '', quantidade: l.quantity })))
  }, [contract, eligible, store.logs, store.orders, store.prices])
  async function importFile(file: File) { const data = await file.arrayBuffer(); const wb = XLSX.read(data, { type: 'array' }); const recognized: string[] = []; const unpromoted: string[] = []; let created = 0; let updated = 0; let unchanged = 0
    for (const name of wb.SheetNames) { if (name === '00. LEIA-ME') continue; if (LATER_SHEETS.includes(name)) { unpromoted.push(name); continue }; if (!DATA_SHEETS.includes(name)) continue; recognized.push(name); const rows = XLSX.utils.sheet_to_json<Record<string, unknown>>(wb.Sheets[name], { defval: '' })
      if (name === '03. CADASTRO DE SERVIÇOS') rows.forEach((r) => { const number = get(r, ['Nº OS SABESP', 'N° OS SABESP', 'ID']); if (!number) return; const old = store.calls.find((x) => x.number === number); store.upsertCall({ id: old?.id, contractId: contract.id, number, address: get(r, ['ENDEREÇO', 'ENDERECO']), service: get(r, ['TIPO', 'DESCRIÇÃO DO SERVIÇO']), status: status(get(r, ['STATUS'])), scheduledFor: get(r, ['DATA PROGRAMADA', 'PROGRAMADA']) || undefined }); old ? updated++ : created++ })
      if (name === '05. ORDENS DE SERVIÇO') rows.forEach((r) => { const number = get(r, ['Nº OS SABESP', 'N° OS SABESP', 'OS']); if (!number) return; const call = store.calls.find((x) => x.number === number); const old = store.orders.find((x) => x.number === number); store.upsertOrder({ id: old?.id, contractId: contract.id, callId: call?.id ?? '', number, status: status(get(r, ['STATUS'])), beforePhotos: [], afterPhotos: [], pavementRestored: false }); old ? updated++ : created++ })
      if (name === '02. TABELA DE PREÇOS') rows.forEach((r) => { const key = get(r, ['CHAVE', 'N. PREÇO', 'Nº PREÇO']); if (!key || store.prices.some((p) => p.contractId === contract.id && p.key === key)) { unchanged++; return }; store.setSlice({ prices: [...store.prices, { id: crypto.randomUUID(), contractId: contract.id, key, description: get(r, ['DESCRIÇÃO DO SERVIÇO', 'ITEM SABESP']), unit: get(r, ['UN']), value: Number(get(r, ['R$ UNIT', 'VALOR']).replace(',', '.')) || 0 }] }); created++ })
    }
    const batch = { id: crypto.randomUUID(), filename: file.name, createdAt: new Date().toISOString(), recognized, unpromoted, created, updated, unchanged }; store.setSlice({ imports: [batch, ...store.imports] }); setMessage(`${created} criado(s), ${updated} atualizado(s), ${unchanged} sem mudança. ${unpromoted.length} aba(s) reconhecida(s), preservadas para a próxima fase.`) }
  return <section className="flex min-h-0 flex-1 flex-col overflow-auto bg-[#1f1f1f] p-5 text-white"><div className="mb-4"><h2 className="text-xl font-bold">Operacional Sabesp</h2><p className="text-sm text-[#a3a3a3]">Chamados → Programação → OS → Apontamento → Materiais → Medição</p></div><div className="mb-5 flex gap-2 overflow-x-auto border-b border-[#525252] pb-2">{tabs.map((t) => <button key={t.id} onClick={() => setTab(t.id)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs ${tab === t.id ? 'bg-[#f97316] text-white' : 'text-[#a3a3a3] hover:bg-[#333]'}`}><t.icon className="mr-1 inline" size={14}/>{t.label}</button>)}</div>
    {tab === 'chamados' && <Grid title="Chamados Sabesp" columns={['Número', 'Endereço', 'Serviço', 'Status']} rows={store.calls.map((x) => [x.number, x.address, x.service, x.status])}/>} {tab === 'programacao' && <Grid title="Programação Diária" columns={['Chamado', 'Data', 'Status']} rows={store.calls.filter((x) => x.scheduledFor).map((x) => [x.number, x.scheduledFor!, x.status])}/>} {tab === 'os' && <Grid title="Ordens de Serviço" columns={['OS', 'Status', 'Evidências', 'Pavimento']} rows={store.orders.map((x) => [x.number, x.status, `${x.beforePhotos.length} antes / ${x.afterPhotos.length} depois`, x.pavementRestored ? 'Confirmado' : 'Pendente'])}/>} {tab === 'apontamento' && <Grid title="Apontamento Diário" columns={['OS', 'Data', 'Quantidade']} rows={store.logs.map((x) => [store.orders.find((o) => o.id === x.orderId)?.number ?? '—', x.date, String(x.quantity)])}/>} {tab === 'materiais' && <Grid title="Materiais por OS" columns={['OS', 'Material', 'Quantidade']} rows={store.logs.filter((x) => x.material).map((x) => [x.orderId, x.material!, String(x.quantity)])}/>} {tab === 'equipe' && <><Grid title="Equipe Operacional" columns={['Nome', 'Função', 'CNH por contrato', 'Validade']} rows={store.crews.map((x) => [x.name, x.role, x.cnhCategory ?? '—', x.cnhExpiresAt ?? '—'])}/><p className="mt-3 text-xs text-[#fbbf24]">CNH está conscientemente restrita a este contrato operacional; não duplica número de documento do cadastro geral.</p></>} {tab === 'medicao' && <div className="rounded-xl border border-[#525252] bg-[#2c2c2c] p-4"><h3 className="font-bold">Medição Sabesp</h3><p className="mt-2 text-sm">Elegíveis: {eligible.length} · bloqueadas por evidência: {pendingEvidence.length}</p><p className="mt-1 text-sm">Total pelo motor de medição: R$ {measurement.total.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</p><p className="mt-1 text-xs text-[#a3a3a3]">{measurement.podeFechar && pendingEvidence.length === 0 ? 'Pode fechar.' : 'Não pode fechar: preço pendente ou OS sem fotos antes/depois e pavimento reposto.'}</p></div>} {tab === 'importar' && <div className="rounded-xl border border-dashed border-[#f97316]/60 bg-[#2c2c2c] p-6"><input ref={input} type="file" accept=".xlsx,.xls,.ods,.csv" className="hidden" onChange={(e) => e.target.files?.[0] && void importFile(e.target.files[0])}/><button onClick={() => input.current?.click()} className="rounded-lg bg-[#f97316] px-4 py-2 text-sm font-semibold"><Upload className="mr-2 inline" size={16}/>Importar Excel, ODS ou CSV</button><p className="mt-3 text-xs text-[#a3a3a3]">Reconhece 16 abas de dados; 00. LEIA-ME é documentação. Banco de Custos, Carteira/Ticket, Diário, Faturamento, Resumo e Dashboard ficam reconhecidos, sem promoção indevida.</p>{message && <p className="mt-3 text-sm text-green-400">{message}</p>}</div>}</section>
}
function Grid({ title, columns, rows }: { title: string; columns: string[]; rows: string[][] }) { return <div className="overflow-auto rounded-xl border border-[#525252] bg-[#2c2c2c]"><h3 className="px-4 py-3 font-bold">{title}</h3><table className="w-full text-left text-xs"><thead className="bg-[#3d3d3d] text-[#a3a3a3]"><tr>{columns.map((c) => <th key={c} className="px-4 py-2">{c}</th>)}</tr></thead><tbody>{rows.map((r, i) => <tr key={i} className="border-t border-[#525252] even:bg-white/[.03]">{r.map((v, j) => <td key={j} className="px-4 py-2">{v || '—'}</td>)}</tr>)}{!rows.length && <tr><td colSpan={columns.length} className="px-4 py-8 text-center text-[#a3a3a3]">Nenhum registro importado ainda.</td></tr>}</tbody></table></div> }
