/** Dados operacionais importados do workbook Sabesp. Cada aba preserva todas as colunas
 * originais: o sistema não descarta uma coluna nova da planilha enquanto ela ainda não tiver UI própria. */
import { create } from 'zustand'
import { attachBlobSync } from '@/lib/blobSync'

export type SabespSheetId = 'configuracoes' | 'banco_custos' | 'carteira_ticket' | 'tabela_precos' | 'cadastro_servicos' | 'programacao' | 'ordens_servico' | 'apontamento' | 'materiais' | 'equipe' | 'medicao' | 'diario_obra' | 'ocorrencias' | 'faturamento' | 'resumo' | 'dashboard' | 'atas' | 'lookahead' | 'plano_semanal' | 'planejado_realizado'
export interface SabespSheetDefinition { id: SabespSheetId; sheetName: string; label: string; keyColumns: string[]; readonly?: boolean }
export const SABESP_SHEETS: SabespSheetDefinition[] = [
  { id: 'configuracoes', sheetName: '01. CONFIGURAÇÕES', label: 'Configurações', keyColumns: ['Empresa executante'] }, { id: 'banco_custos', sheetName: '01A. BANCO DE CUSTOS', label: 'Banco de Custos', keyColumns: ['ITEM', 'CUSTO MENSAL'] }, { id: 'carteira_ticket', sheetName: '01B. CARTEIRA E TICKET', label: 'Carteira e Ticket', keyColumns: ['TIPO DE SERVIÇO', 'CONTRATO'] }, { id: 'tabela_precos', sheetName: '02. TABELA DE PREÇOS', label: 'Tabela de Preços', keyColumns: ['CHAVE'], readonly: true }, { id: 'cadastro_servicos', sheetName: '03. CADASTRO DE SERVIÇOS', label: 'Cadastro de Serviços', keyColumns: ['ID', 'CONTRATO'] }, { id: 'programacao', sheetName: '04. PROGRAMAÇÃO DIÁRIA', label: 'Programação Diária', keyColumns: ['DATA', 'CONTRATO', 'EQUIPE', 'ID DO SERVIÇO'] }, { id: 'ordens_servico', sheetName: '05. ORDENS DE SERVIÇO', label: 'Ordens de Serviço', keyColumns: ['ID DO SERVIÇO', 'CONTRATO', 'Nº OS SABESP'] }, { id: 'apontamento', sheetName: '06. APONTAMENTO DIÁRIO', label: 'Apontamento Diário', keyColumns: ['DATA', 'CONTRATO', 'EQUIPE'] }, { id: 'materiais', sheetName: '07. MATERIAIS', label: 'Materiais', keyColumns: ['DATA', 'ID DO SERVIÇO / OS', 'MATERIAL', 'MOVIMENTO'] }, { id: 'equipe', sheetName: '08. EQUIPE', label: 'Equipe', keyColumns: ['MATRÍCULA', 'CONTRATO'] }, { id: 'medicao', sheetName: '09. MEDIÇÃO', label: 'Medição', keyColumns: ['Nº BOLETIM', 'ID DO SERVIÇO', 'CÓD. PREÇO (CHAVE)'] }, { id: 'diario_obra', sheetName: '10. DIÁRIO DE OBRA', label: 'Diário de Obra', keyColumns: ['Nº DO RDO', 'CONTRATO'] }, { id: 'ocorrencias', sheetName: '11. OCORRÊNCIAS', label: 'Ocorrências', keyColumns: ['Nº', 'CONTRATO'] }, { id: 'faturamento', sheetName: '12. FATURAMENTO', label: 'Faturamento', keyColumns: ['MÊS', 'CONTRATO'] }, { id: 'resumo', sheetName: '13. RESUMO GERENCIAL', label: 'Resumo Gerencial', keyColumns: ['MÊS DE REFERÊNCIA'], readonly: true }, { id: 'dashboard', sheetName: '14. DASHBOARD', label: 'Dashboard', keyColumns: ['SERVIÇOS EXECUTADOS NO MÊS'], readonly: true }, { id: 'atas', sheetName: '15. ATAS DE REUNIÃO', label: 'Atas de Reunião', keyColumns: ['Nº DA ATA', 'PENDÊNCIA / AÇÃO'] }, { id: 'lookahead', sheetName: '16. LOOKAHEAD E RESTRIÇÕES', label: 'Lookahead e Restrições', keyColumns: ['SEMANA (2ª feira)', 'CONTRATO', 'ID DO SERVIÇO'] }, { id: 'plano_semanal', sheetName: '17. PLANO SEMANAL E PPC', label: 'Plano Semanal e PPC', keyColumns: ['SEMANA (2ª feira)', 'CONTRATO', 'ID DO SERVIÇO'] }, { id: 'planejado_realizado', sheetName: '18. PLANEJADO x REALIZADO', label: 'Planejado × Realizado', keyColumns: ['SEMANA (2ª feira)'], readonly: true },
]
export interface SabespRow { key: string; values: Record<string, string | number | boolean | null>; active: boolean; importedAt: string }
export interface SabespSheetData { headers: string[]; rows: SabespRow[]; sourceName: string }
export interface SabespGuide { title: string; lines: string[] }
export interface SabespDropdown { sheet: string; range: string; listName: string; options: string[]; message?: string; required: boolean }
export interface SabespImportBatch { id: string; filename: string; createdAt: string; recognized: string[]; created: number; updated: number; unchanged: number; archived: number; rejected: string[]; formulas: number; dropdowns: number }
interface State { sheets: Partial<Record<SabespSheetId, SabespSheetData>>; guides: { quick?: SabespGuide; readme?: SabespGuide }; dropdowns: SabespDropdown[]; imports: SabespImportBatch[]; applyWorkbook: (input: { filename: string; sheets: Partial<Record<SabespSheetId, SabespSheetData>>; rejected: string[]; guides?: State['guides']; dropdowns?: SabespDropdown[]; formulas?: number }) => SabespImportBatch; setSlice: (patch: Partial<State>) => void }
const same = (a: SabespRow, b: SabespRow) => JSON.stringify(a.values) === JSON.stringify(b.values)
export const useSabespStore = create<State>((set, get) => ({
  sheets: {}, guides: {}, dropdowns: [], imports: [],
  applyWorkbook: ({ filename, sheets, rejected, guides, dropdowns, formulas = 0 }) => { let created = 0, updated = 0, unchanged = 0, archived = 0; const now = new Date().toISOString(); const next: Partial<Record<SabespSheetId, SabespSheetData>> = { ...get().sheets }
    for (const definition of SABESP_SHEETS) { const incoming = sheets[definition.id]; if (!incoming) continue; const old = get().sheets[definition.id]; const oldByKey = new Map(old?.rows.map((row) => [row.key, row]) ?? []); const incomingKeys = new Set(incoming.rows.map((row) => row.key)); const rows = incoming.rows.map((row) => { const prior = oldByKey.get(row.key); if (!prior) { created++; return { ...row, active: true, importedAt: now } }; if (same(prior, row) && prior.active) { unchanged++; return prior }; updated++; return { ...row, active: true, importedAt: now } }); for (const prior of old?.rows ?? []) if (!incomingKeys.has(prior.key) && prior.active) { rows.push({ ...prior, active: false, importedAt: now }); archived++ }; next[definition.id] = { ...incoming, rows } }
    const batch: SabespImportBatch = { id: crypto.randomUUID(), filename, createdAt: now, recognized: Object.keys(sheets), created, updated, unchanged, archived, rejected, formulas, dropdowns: dropdowns?.length ?? 0 }; set({ sheets: next, guides: guides ?? get().guides, dropdowns: dropdowns ?? get().dropdowns, imports: [batch, ...get().imports].slice(0, 50) }); return batch },
  setSlice: (patch) => set(patch),
}))
attachBlobSync(useSabespStore, { key: 'operacional-sabesp-rev15', getSlice: (s) => ({ sheets: s.sheets, guides: s.guides, dropdowns: s.dropdowns, imports: s.imports }), applySlice: (slice) => useSabespStore.getState().setSlice(slice as Partial<State>) })
