import { useMemo, useRef, useState } from 'react'
import { AlertTriangle, CheckCircle2, FileSpreadsheet, HelpCircle, Upload } from 'lucide-react'
import * as XLSX from 'xlsx'
import JSZip from 'jszip'
import { SABESP_SHEETS, type SabespDropdown, type SabespGuide, type SabespSheetData, type SabespSheetId, useSabespStore } from './sabespStore'

const norm = (v: unknown) => String(v ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toUpperCase().replace(/\s+/g, ' ').trim()
const scalar = (v: unknown) => v instanceof Date ? v.toISOString().slice(0, 10) : (typeof v === 'string' ? v.trim() : v as string | number | boolean | null)
function parseSheet(sheet: XLSX.WorkSheet, id: SabespSheetId): SabespSheetData | null {
  const cfg = SABESP_SHEETS.find((item) => item.id === id)!; const matrix = XLSX.utils.sheet_to_json<unknown[]>(sheet, { header: 1, defval: '', raw: false })
  let best = -1; let score = 0
  matrix.slice(0, 20).forEach((row, index) => { const cells = row.map(norm); const candidate = cfg.keyColumns.reduce((sum, key) => { const wanted = norm(key); return sum + (cells.some((cell) => cell === wanted || cell.startsWith(wanted)) ? 1 : 0) }, 0); if (candidate > score) { score = candidate; best = index } })
  if (best < 0 || score === 0) return null
  const headers = matrix[best].map((cell, i) => String(cell || `Coluna ${i + 1}`).trim()); const rows = matrix.slice(best + 1).map((raw) => Object.fromEntries(headers.map((header, i) => [header, scalar(raw[i])]))).filter((row) => Object.values(row).some((v) => String(v ?? '').trim()))
  const seen = new Map<string, number>(); const parsed = rows.map((values) => { const base = cfg.keyColumns.map((key) => String(values[key] ?? '')).join('|').trim() || JSON.stringify(values); const n = seen.get(base) ?? 0; seen.set(base, n + 1); return { key: `${base}#${n}`, values, active: true, importedAt: '' } })
  return { headers, rows: parsed, sourceName: cfg.sheetName }
}
type Candidate = { filename: string; sheets: Partial<Record<SabespSheetId, SabespSheetData>>; rejected: string[] }
const textOf = (matrix: unknown[][], title: string): SabespGuide => ({ title, lines: matrix.flatMap((row) => row.map((cell) => String(cell ?? '').trim()).filter(Boolean)).filter((line, index, lines) => lines.indexOf(line) === index) })
function namedList(wb: XLSX.WorkBook, name: string) { const ref = wb.Workbook?.Names?.find((item) => item.Name === name)?.Ref; const match = ref?.match(/^'?(.*?)'?\!\$([A-Z]+)\$(\d+):\$([A-Z]+)\$(\d+)$/); if (!match) return []; const sheet = wb.Sheets[match[1]]; if (!sheet) return []; const range = XLSX.utils.decode_range(`${match[2]}${match[3]}:${match[4]}${match[5]}`); const values: string[] = []; for (let r = range.s.r; r <= range.e.r; r++) { const value = sheet[XLSX.utils.encode_cell({ r, c: range.s.c })]?.v; if (value != null && String(value).trim()) values.push(String(value).trim()) } return [...new Set(values)] }
async function dropdownsFromXlsx(buffer: ArrayBuffer, wb: XLSX.WorkBook): Promise<SabespDropdown[]> { const zip = await JSZip.loadAsync(buffer); const out: SabespDropdown[] = []; for (let index = 0; index < wb.SheetNames.length; index++) { const xml = await zip.file(`xl/worksheets/sheet${index + 1}.xml`)?.async('text'); if (!xml) continue; for (const match of xml.matchAll(/<dataValidation\s+([^>]*)>([\s\S]*?)<\/dataValidation>/g)) { const attrs = match[1]; const body = match[2]; const listName = body.match(/<formula1>([^<]+)<\/formula1>/)?.[1] ?? ''; if (!listName) continue; const message = attrs.match(/(?:prompt|error)="([^"]+)"/)?.[1]; const range = attrs.match(/sqref="([^"]+)"/)?.[1] ?? ''; out.push({ sheet: wb.SheetNames[index], range, listName, options: namedList(wb, listName), message, required: !/allowBlank="1"/.test(attrs) }) } } return out }
export function SabespPanel() {
  const { sheets, guides, dropdowns, imports, applyWorkbook } = useSabespStore(); const [active, setActive] = useState<SabespSheetId>('cadastro_servicos'); const [candidate, setCandidate] = useState<(Candidate & { guides: { quick?: SabespGuide; readme?: SabespGuide }; dropdowns: SabespDropdown[]; formulas: number; missingOperational: string[] }) | null>(null); const [configView, setConfigView] = useState<'dados' | 'guia' | 'leia' | 'listas'>('dados'); const input = useRef<HTMLInputElement>(null)
  const data = sheets[active]; const activeRows = data?.rows.filter((row) => row.active) ?? []
  const metrics = useMemo(() => ({ chamados: sheets.cadastro_servicos?.rows.filter((x) => x.active).length ?? 0, os: sheets.ordens_servico?.rows.filter((x) => x.active).length ?? 0, pendencias: sheets.ocorrencias?.rows.filter((x) => x.active && /ABERTA|PENDENTE/i.test(String(x.values.STATUS ?? ''))).length ?? 0, valor: (sheets.medicao?.rows ?? []).filter((x) => x.active).reduce((sum, x) => sum + Number(String(x.values['VALOR APROVADO'] ?? x.values.VALOR ?? 0).replace('.', '').replace(',', '.')), 0) }), [sheets])
  const alerts = useMemo(() => { const out: string[] = []; for (const row of sheets.ordens_servico?.rows ?? []) if (row.active && /CONCLU/i.test(String(row.values['STATUS DA OS'] ?? '')) && (!row.values['FOTO ANTES'] || !row.values['FOTO DEPOIS'] || !/SIM/i.test(String(row.values['PAVIMENTO REPOSTO?'] ?? '')))) out.push(`OS ${row.values['ID DO SERVIÇO'] ?? row.key}: evidência ou pavimento pendente`); for (const row of sheets.ocorrencias?.rows ?? []) if (row.active && /ABERTA|PENDENTE/i.test(String(row.values.STATUS ?? ''))) out.push(`Ocorrência ${row.values.Nº ?? row.key}: pendente`); for (const row of sheets.lookahead?.rows ?? []) if (row.active && /RESTRI|NÃO|NAO/i.test(String(row.values.SITUAÇÃO ?? row.values['RESTRIÇÕES PENDENTES'] ?? ''))) out.push(`Lookahead ${row.values['ID DO SERVIÇO'] ?? row.key}: restrição pendente`); for (const row of sheets.equipe?.rows ?? []) if (row.active && /VENC|ALERTA/i.test(String(row.values.ALERTA ?? ''))) out.push(`Equipe ${row.values.NOME ?? row.key}: validade a conferir`); return out }, [sheets])
  async function selectFile(file: File) { try { const buffer = await file.arrayBuffer(); const wb = XLSX.read(buffer, { type: 'array', cellDates: true, cellFormula: true }); const found: Candidate['sheets'] = {}; const rejected: string[] = []; let formulas = 0; for (const definition of SABESP_SHEETS) { const exact = wb.Sheets[definition.sheetName] ?? Object.entries(wb.Sheets).find(([name]) => norm(name).includes(norm(definition.sheetName).replace(/^\d+[A-Z]?\.\s*/, '')))?.[1]; if (!exact) { rejected.push(`${definition.label}: aba não encontrada`); continue }; const parsed = parseSheet(exact, definition.id); if (!parsed) rejected.push(`${definition.label}: cabeçalho não reconhecido`); else found[definition.id] = parsed; Object.values(exact).forEach((cell) => { if (typeof cell === 'object' && cell && 'f' in cell) formulas++ }) }; const guide = wb.Sheets['GUIA RÁPIDO']; const readme = wb.Sheets['00. LEIA-ME']; if (!guide) rejected.push('Guia Rápido: aba opcional não encontrada'); if (!readme) rejected.push('Leia-me: aba opcional não encontrada'); const missingOperational = SABESP_SHEETS.filter((definition) => !found[definition.id]).map((definition) => definition.label); const ds = file.name.toLowerCase().endsWith('.xlsx') ? await dropdownsFromXlsx(buffer, wb) : []; setCandidate({ filename: file.name, sheets: found, rejected, guides: { quick: guide ? textOf(XLSX.utils.sheet_to_json(guide, { header: 1, defval: '' }), 'Guia Rápido') : undefined, readme: readme ? textOf(XLSX.utils.sheet_to_json(readme, { header: 1, defval: '' }), 'Leia-me') : undefined }, dropdowns: ds, formulas, missingOperational }) } catch { setCandidate({ filename: file.name, sheets: {}, rejected: ['Não foi possível ler o arquivo. Use Excel, ODS ou CSV exportado.'], guides: {}, dropdowns: [], formulas: 0, missingOperational: SABESP_SHEETS.map((x) => x.label) }) } }
  const predicted = candidate && Object.values(candidate.sheets).reduce((sum, sheet) => sum + (sheet?.rows.length ?? 0), 0)
  return <section className="min-h-0 flex-1 overflow-auto bg-[#1f1f1f] p-5 text-white"><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-bold">Operacional Sabesp</h2><p className="text-sm text-[#a3a3a3]">A cópia operacional da planilha: importação, acompanhamento e fechamento do contrato.</p></div><div><input ref={input} type="file" accept=".xlsx,.xls,.ods,.csv" className="hidden" onChange={(e) => e.target.files?.[0] && void selectFile(e.target.files[0])}/><button onClick={() => input.current?.click()} className="inline-flex items-center gap-2 rounded-lg bg-[#f97316] px-4 py-2 text-sm font-semibold hover:bg-[#ea580c]"><Upload size={16}/>Importar planilha atualizada</button></div></div>
    <div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Chamados', metrics.chamados], ['OS', metrics.os], ['Ocorrências abertas', metrics.pendencias], ['Medição aprovada', metrics.valor ? `R$ ${metrics.valor.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}` : '—']].map(([label, value]) => <div key={String(label)} className="rounded-xl border border-[#525252] bg-[#2c2c2c] p-3"><p className="text-[11px] text-[#a3a3a3]">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div>)}</div>
    {alerts.length > 0 && <div className="mb-4 rounded-xl border border-[#f59e0b]/40 bg-[#f59e0b]/10 p-3"><p className="text-xs font-semibold text-[#fbbf24]">{alerts.length} alerta(s) gerado(s) pelos dados importados</p><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1">{alerts.slice(0, 6).map((alert) => <span key={alert} className="text-[11px] text-[#e5e5e5]">{alert}</span>)}</div></div>}
    <div className="mb-4 flex gap-2 overflow-x-auto border-b border-[#525252] pb-2">{SABESP_SHEETS.map((item) => <button key={item.id} onClick={() => setActive(item.id)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-xs ${active === item.id ? 'bg-[#f97316] text-white' : 'text-[#a3a3a3] hover:bg-[#333]'}`}>{item.label}</button>)}</div>
    {active === 'configuracoes' && <div className="mb-4 rounded-xl border border-[#525252] bg-[#2c2c2c] p-3"><div className="mb-3 flex flex-wrap gap-2">{([['dados', 'Parâmetros e listas'], ['guia', 'Guia Rápido'], ['leia', 'Leia-me'], ['listas', `Dropdowns (${dropdowns.length})`]] as const).map(([key, label]) => <button key={key} onClick={() => setConfigView(key)} className={`rounded-lg px-3 py-1.5 text-xs ${configView === key ? 'bg-[#f97316] text-white' : 'bg-[#3d3d3d] text-[#a3a3a3]'}`}>{label}</button>)}</div>{configView === 'guia' && <Guide guide={guides.quick}/>} {configView === 'leia' && <Guide guide={guides.readme}/>} {configView === 'listas' && <div className="max-h-52 overflow-auto text-xs">{dropdowns.map((drop, i) => <div key={`${drop.sheet}-${drop.range}-${i}`} className="border-b border-[#525252] py-2"><b>{drop.sheet}</b> · {drop.range} → <span className="text-[#f97316]">{drop.listName}</span><span className="ml-2 text-[#a3a3a3]">{drop.options.join(' · ') || 'lista sem opções resolvidas'}</span></div>)}{!dropdowns.length && <p className="text-[#a3a3a3]">Importe um arquivo .xlsx para carregar as validações de seleção.</p>}</div>}</div>}
    <div className="rounded-xl border border-[#525252] bg-[#2c2c2c]"><div className="flex items-center justify-between border-b border-[#525252] px-4 py-3"><div><h3 className="font-semibold">{SABESP_SHEETS.find((item) => item.id === active)?.label}</h3><p className="text-xs text-[#a3a3a3]">{activeRows.length} registro(s) ativo(s) importado(s)</p></div><span className="inline-flex items-center gap-1 text-xs text-[#a3a3a3]"><HelpCircle size={13}/>Dados completos da planilha</span></div><div className="max-h-[55vh] overflow-auto"><table className="min-w-full text-left text-xs"><thead className="sticky top-0 bg-[#3d3d3d] text-[#a3a3a3]"><tr>{(data?.headers ?? ['Importe a planilha para carregar esta aba']).map((header) => <th key={header} className="whitespace-nowrap px-3 py-2.5 font-medium">{header}</th>)}</tr></thead><tbody>{activeRows.map((row) => <tr key={row.key} className="border-t border-[#525252] even:bg-white/[.03]">{(data?.headers ?? []).map((header) => <td key={header} className="max-w-64 whitespace-nowrap px-3 py-2" title={String(row.values[header] ?? '')}>{String(row.values[header] ?? '—')}</td>)}</tr>)}{!activeRows.length && <tr><td className="px-4 py-12 text-center text-[#a3a3a3]">Nenhum dado importado nesta aba.</td></tr>}</tbody></table></div></div>
    {candidate && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-2xl border border-[#525252] bg-[#2c2c2c] p-5 shadow-2xl"><div className="flex items-center gap-2"><FileSpreadsheet className="text-[#f97316]" size={20}/><div><h3 className="font-bold">Conferir importação</h3><p className="text-xs text-[#a3a3a3]">{candidate.filename}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="Abas operacionais" value={`${Object.keys(candidate.sheets).length}/20`}/><Stat label="Linhas lidas" value={predicted ?? 0}/><Stat label="Fórmulas" value={candidate.formulas}/><Stat label="Dropdowns" value={candidate.dropdowns.length}/></div>{candidate.rejected.length > 0 && <div className="mt-4 rounded-lg border border-[#f59e0b]/40 bg-[#f59e0b]/10 p-3 text-xs text-[#fbbf24]"><AlertTriangle className="mr-1 inline" size={13}/>{candidate.rejected.join(' · ')}</div>}{candidate.missingOperational.length > 0 && <p className="mt-3 text-xs text-[#f87171]">Importação bloqueada: faltam abas obrigatórias: {candidate.missingOperational.join(', ')}.</p>}<p className="mt-4 text-xs text-[#a3a3a3]">Guias, fórmulas, listas e validações serão sincronizados junto com os dados. A planilha continua sendo a fonte oficial.</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setCandidate(null)} className="rounded-lg px-4 py-2 text-sm text-[#a3a3a3]">Cancelar</button><button onClick={() => { applyWorkbook(candidate); setCandidate(null) }} disabled={candidate.missingOperational.length > 0} className="inline-flex items-center gap-2 rounded-lg bg-[#22c55e] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40"><CheckCircle2 size={16}/>Aplicar atualização</button></div></div></div>}
    {imports[0] && <p className="mt-3 text-xs text-[#6b6b6b]">Última importação: {imports[0].filename} · {imports[0].created} novos · {imports[0].updated} atualizados · {imports[0].unchanged} inalterados · {imports[0].archived} arquivados.</p>}
  </section>
}
function Stat({ label, value }: { label: string; value: string | number }) { return <div className="rounded-lg border border-[#525252] bg-[#333] p-2.5"><p className="text-[10px] text-[#a3a3a3]">{label}</p><p className="mt-1 font-bold text-[#f5f5f5]">{value}</p></div> }
function Guide({ guide }: { guide?: SabespGuide }) { return <div className="max-h-52 overflow-auto whitespace-pre-wrap text-xs leading-relaxed text-[#d4d4d4]">{guide?.lines.map((line, index) => <p key={`${line}-${index}`} className="mb-1">{line}</p>) ?? <p className="text-[#a3a3a3]">Este guia será carregado na próxima importação.</p>}</div> }
