import * as XLSX from 'xlsx'
import type { Contractor } from '@/store/contractorStore'
import type {
  Subempreiteiro,
  SubempreiteiroCustoLancamento,
  SubempreiteiroDescontoMensal,
  SubempreiteiroMemoriaLinha,
  SubempreiteiroNotaFiscal,
  SubempreiteiroParametroFinanceiro,
  SubempreiteiroParametroMensal,
  SubempreteiroItem,
} from '@/store/medicaoBillingStore'
import type {
  UnifiedMeasurementContractItem,
  UnifiedMeasurementFinancialEntry,
  UnifiedMeasurementMemoryLine,
  UnifiedMeasurementPeriod,
  UnifiedMeasurementSource,
} from '@/store/medicaoUnificadaStore'

export type MeasurementGenerationExceptionCode =
  | 'source_without_contractor'
  | 'missing_n_preco'
  | 'missing_unit_price'
  | 'blocked_quality'
  | 'unapproved_financial'
  | 'missing_invoice'
  | 'closing_divergence'

export type MeasurementGenerationSeverity = 'blocker' | 'warning'

export interface MeasurementGenerationException {
  code: MeasurementGenerationExceptionCode
  severity: MeasurementGenerationSeverity
  message: string
  sourceId?: string
  valueBRL?: number
}

export interface GeneratedMeasurementEconomySignals {
  autoGeneratedLines: number
  evidenceCoveragePercent: number
  pendingCriticalCount: number
  grossApprovedBRL: number
  netPreviewBRL: number
  invoiceGapBRL: number
}

export interface GeneratedSubempreiteiroMeasurement {
  key: string
  periodId: string | null
  periodLabel: string
  contractNo: string
  contractorId: string | null
  contractorName: string
  nucleo: string
  payload: Subempreiteiro
  sources: UnifiedMeasurementSource[]
  memoryLines: UnifiedMeasurementMemoryLine[]
  financialEntries: UnifiedMeasurementFinancialEntry[]
  exceptions: MeasurementGenerationException[]
  economy: GeneratedMeasurementEconomySignals
}

export interface GenerateSubempreiteiroMeasurementInput {
  period: UnifiedMeasurementPeriod | null
  contractors: Contractor[]
  sources: UnifiedMeasurementSource[]
  memoryLines: UnifiedMeasurementMemoryLine[]
  contractItems: UnifiedMeasurementContractItem[]
  financialEntries: UnifiedMeasurementFinancialEntry[]
  contractorId?: string | null
  nucleo?: string | null
}

const FINANCIAL_DEDUCTION_TYPES = new Set([
  'retention',
  'discount',
  'rh',
  'machine',
  'vehicle',
  'fuel',
  'material',
  'epi',
  'third_party_service',
  'advance',
  'previous_closing',
  'other',
  'manual_adjustment',
])

const approvedStatuses = new Set(['approved', 'paid'])
const num = (value: unknown) => Number.isFinite(Number(value)) ? Number(value) : 0
const roundMoney = (value: number) => Math.round(value * 100) / 100

export function generateAllSubempreiteiroMeasurements(input: GenerateSubempreiteiroMeasurementInput): GeneratedSubempreiteiroMeasurement[] {
  const keys = new Map<string, { contractorId: string | null; nucleo: string }>()
  const addKey = (contractorId: string | null | undefined, nucleo: string | null | undefined) => {
    const cleanContractor = contractorId || null
    const cleanNucleo = nucleo?.trim() || 'Sem nucleo'
    keys.set(`${cleanContractor ?? 'sem-empreiteiro'}|${cleanNucleo}`, { contractorId: cleanContractor, nucleo: cleanNucleo })
  }

  for (const source of input.sources) addKey(source.contractor_id, source.nucleo)
  for (const line of input.memoryLines) addKey(line.contractor_id, line.nucleo)
  for (const entry of input.financialEntries) addKey(entry.contractor_id, entry.nucleo)

  return Array.from(keys.values())
    .map((key) => generateSubempreiteiroMeasurement({ ...input, contractorId: key.contractorId, nucleo: key.nucleo }))
    .sort((a, b) => a.contractorName.localeCompare(b.contractorName) || a.nucleo.localeCompare(b.nucleo))
}

export function generateSubempreiteiroMeasurement(input: GenerateSubempreiteiroMeasurementInput): GeneratedSubempreiteiroMeasurement {
  const periodLabel = input.period?.period_label || 'sem-periodo'
  const contractNo = input.period?.contract_no || ''
  const contractorId = input.contractorId || null
  const nucleo = input.nucleo?.trim() || 'Sem nucleo'
  const contractor = contractorId ? input.contractors.find((item) => item.id === contractorId) : null
  const contractorName = contractor?.name || 'Sem empreiteiro'
  const key = `${input.period?.id ?? 'no-period'}:${contractorId ?? 'no-contractor'}:${nucleo}`

  const scopedSources = input.sources.filter((source) => sameScope(source.contractor_id, source.nucleo, contractorId, nucleo))
  const scopedMemory = input.memoryLines.filter((line) => sameScope(line.contractor_id, line.nucleo, contractorId, nucleo))
  const scopedFinancial = input.financialEntries.filter((entry) => sameScope(entry.contractor_id, entry.nucleo, contractorId, nucleo))
  const contractById = new Map(input.contractItems.map((item) => [item.id, item]))
  const contractByNPreco = new Map(input.contractItems.filter((item) => item.n_preco).map((item) => [normalizeCode(item.n_preco), item]))

  const memoria: SubempreiteiroMemoriaLinha[] = scopedMemory.map((line) => memoryToSubLine(line, periodLabel))
  const itens = consolidateItems(scopedMemory, contractById, contractByNPreco, periodLabel)
  const detalhadoMensal = itens.map((item, index) => ({
    id: `det-${key}-${index}`,
    mes: periodLabel,
    item: item.nPrecoSabesp || item.nPreco,
    descricao: item.descricao,
    nPreco: item.nPreco,
    unidade: item.unidade,
    qtdContratada: 0,
    precoUnitario: item.valorUnitario,
    precoTotal: item.qtd * item.valorUnitario,
    qtdMes: item.qtd,
    precoTotalMes: item.qtd * item.valorUnitario,
    fisicoMes: item.qtd,
    financeiroMes: item.qtd * item.valorUnitario,
    origem: 'RDO Sabesp' as const,
    status: 'aprovado' as const,
  }))

  const grossMeasured = roundMoney(scopedMemory.reduce((sum, line) => sum + num(line.quantity) * resolvedUnitPrice(line, contractById, contractByNPreco), 0))
  const grossApproved = roundMoney(scopedMemory
    .filter((line) => line.review_status === 'approved')
    .reduce((sum, line) => sum + num(line.quantity) * resolvedUnitPrice(line, contractById, contractByNPreco), 0))
  const deductions = roundMoney(scopedFinancial
    .filter((entry) => approvedStatuses.has(entry.status) && FINANCIAL_DEDUCTION_TYPES.has(entry.entry_type))
    .reduce((sum, entry) => sum + Math.abs(num(entry.amount)), 0))
  const invoices = roundMoney(scopedFinancial
    .filter((entry) => approvedStatuses.has(entry.status) && entry.entry_type === 'invoice')
    .reduce((sum, entry) => sum + Math.abs(num(entry.amount)), 0))
  const retention = roundMoney(scopedFinancial
    .filter((entry) => approvedStatuses.has(entry.status) && entry.entry_type === 'retention')
    .reduce((sum, entry) => sum + Math.abs(num(entry.amount)), 0))
  const netPreview = roundMoney(grossApproved - deductions)

  const descontos = buildDescontos(scopedFinancial, periodLabel)
  const custos = buildOperationalCostTabs(scopedFinancial, periodLabel)
  const nfs = buildNfs(scopedFinancial, contractorName, periodLabel)
  const parametrosFinanceiros = buildParametrosFinanceiros({
    periodLabel,
    grossMeasured,
    grossApproved,
    deductions,
    invoices,
    netPreview,
    scopedFinancial,
  })
  const parametros: SubempreiteiroParametroMensal[] = [{
    id: `param-${key}`,
    mes: periodLabel,
    descricao: 'Resumo gerado automaticamente pela Medicao Unificada',
    valor: netPreview,
    medicaoAprovada: grossApproved,
    valorMaisDescontos: grossApproved - deductions,
    empreiteiro: contractorName,
    nucleo,
    contrato: contractNo,
    engenheiro: '',
    gerenteProducao: '',
    revisao: 'AUTO',
    data: new Date().toISOString().slice(0, 10),
    status: hasBlockers(scopedSources, scopedMemory, scopedFinancial) ? 'previa' : 'fechado',
  }]

  const exceptions = buildExceptions({
    sources: scopedSources,
    memoryLines: scopedMemory,
    financialEntries: scopedFinancial,
    grossApproved,
    netPreview,
    invoices,
  })
  const evidenceCoveragePercent = scopedMemory.length > 0
    ? Math.round((scopedMemory.filter((line) => Boolean(line.evidence_url || line.rdo_id || line.source_id)).length / scopedMemory.length) * 100)
    : 0
  const payload: Subempreiteiro = {
    id: key,
    nome: contractorName,
    nucleo,
    periodo: periodLabel,
    contractorId,
    itens,
    memoria,
    parametros,
    descontos,
    ...custos,
    parametrosFinanceiros,
    detalhadoMensal,
    nfs,
    retencoes: [{
      id: `ret-${key}`,
      mes: periodLabel,
      valorRetido: retention,
      valorLiberado: 0,
      saldoAnterior: 0,
      saldoFinal: retention,
      observacao: 'Retencao consolidada por lancamentos financeiros aprovados.',
      origem: 'RDO Sabesp',
    }],
    retencaoItens: itens.filter((item) => num(item.retencaoPercentual) > 0),
    retencaoDetalhada: itens.map((item, index) => ({
      id: `retd-${key}-${index}`,
      mes: periodLabel,
      item: item.nPrecoSabesp || item.nPreco,
      descricao: item.descricao,
      nPreco: item.nPreco,
      unidade: item.unidade,
      qtd: item.qtd,
      precoTotal: item.qtd * item.valorUnitario,
      financeiroMes: item.qtd * item.valorUnitario,
      retencaoPercentual: item.retencaoPercentual ?? 0,
      observacoes: item.retencaoObservacao,
      origem: 'RDO Sabesp',
    })),
    totalMedido: grossMeasured,
    totalAprovado: grossApproved,
    retencao: retention,
  }

  return {
    key,
    periodId: input.period?.id ?? null,
    periodLabel,
    contractNo,
    contractorId,
    contractorName,
    nucleo,
    payload,
    sources: scopedSources,
    memoryLines: scopedMemory,
    financialEntries: scopedFinancial,
    exceptions,
    economy: {
      autoGeneratedLines: scopedMemory.filter((line) => Boolean(line.source_id || line.rdo_id)).length,
      evidenceCoveragePercent,
      pendingCriticalCount: exceptions.filter((item) => item.severity === 'blocker').length,
      grossApprovedBRL: grossApproved,
      netPreviewBRL: netPreview,
      invoiceGapBRL: roundMoney(Math.abs(netPreview - invoices)),
    },
  }
}

export function exportSubempreiteiroWorkbook(measurement: GeneratedSubempreiteiroMeasurement) {
  const wb = XLSX.utils.book_new()
  const sub = measurement.payload
  const descontos = sub.descontos?.[0]
  const parametro = sub.parametros?.[0]
  const nfTotal = (sub.nfs ?? []).reduce((sum, nf) => sum + num(nf.valorNf), 0)
  const netPreview = (sub.parametrosFinanceiros ?? []).find((item) => item.tipo === 'saldo')?.valor ?? sub.totalAprovado - (descontos?.total ?? 0)

  appendSheet(wb, 'Resumo Geral', [
    ['Competencia', sub.periodo],
    ['Descricao', sub.nome],
    ['Nucleo', sub.nucleo],
    ['Contrato', parametro?.contrato ?? measurement.contractNo],
    [],
    ['Campo', 'Valor'],
    ['Medicao enc. Terceiro', sub.totalMedido],
    ['Medicao Aprovada', sub.totalAprovado],
    ['Descontos', -(descontos?.total ?? 0)],
    ['Taxa Adm 5%', -((descontos?.total ?? 0) * 0.05)],
    ['Retencao', -sub.retencao],
    ['Valor NF previsto', netPreview],
    ['NFs aprovadas/pagas', nfTotal],
  ])

  appendSheet(wb, 'RESUMO_FECHAMENTO', [
    ['SLNR - FECHAMENTO DE MEDICAO (EMPREITEIRO)'],
    [],
    ['Mes de Referencia', sub.periodo, 'Empreiteiro', sub.nome],
    ['Obra/Nucleo', sub.nucleo, 'Contrato', parametro?.contrato ?? measurement.contractNo],
    ['Revisao', parametro?.revisao ?? 'AUTO', 'Data', parametro?.data ?? new Date().toISOString().slice(0, 10)],
    [],
    ['Descricao', 'Valor'],
    ['Medicao do periodo', sub.totalMedido],
    ['Medicao aprovada', sub.totalAprovado],
    ['Descontos', -(descontos?.total ?? 0)],
    ['Retencao', -sub.retencao],
    ['Valor liquido previsto', netPreview],
  ])

  appendSheet(wb, 'PARAMETROS', [
    ['Mes', 'Descricao', 'Valor', 'Medicao aprovada', 'Empreiteiro', 'Nucleo', 'Contrato', 'Status'],
    ...(sub.parametros ?? []).map((row) => [row.mes, row.descricao ?? '', row.valor ?? 0, row.medicaoAprovada ?? 0, row.empreiteiro, row.nucleo, row.contrato, row.status]),
    [],
    ['Tipo', 'Descricao', 'Valor', 'Origem'],
    ...(sub.parametrosFinanceiros ?? []).map((row) => [row.tipo, row.descricao, row.valor, row.origem ?? 'Calculado']),
  ])

  appendSheet(wb, 'ITENS RETENCAO', [
    ['N. Preco', 'Descricao', 'Unidade', 'Qtd', 'Valor unitario', 'Valor total', '% retencao'],
    ...(sub.retencaoItens ?? []).map((item) => [item.nPreco, item.descricao, item.unidade, item.qtd, item.valorUnitario, item.qtd * item.valorUnitario, item.retencaoPercentual ?? 0]),
  ])
  appendSheet(wb, 'NFS', [
    ['Numero', 'Fornecedor', 'Valor NF', 'Valor pago', 'Competencia', 'Status', 'Observacao'],
    ...(sub.nfs ?? []).map((nf) => [nf.numero, nf.fornecedor, nf.valorNf, nf.valorPago, nf.competencia, nf.status, nf.observacao]),
  ])
  appendSheet(wb, 'MEDICAO', [
    ['N. Preco', 'Descricao', 'Unidade', 'Qtd mes', 'Valor unitario', 'Total mes', 'Origem', 'RDO'],
    ...sub.itens.map((item) => [item.nPreco, item.descricao, item.unidade, item.qtd, item.valorUnitario, item.qtd * item.valorUnitario, item.origem ?? '', item.rdoId ?? '']),
  ])
  appendSheet(wb, 'MEMORIA', [
    ['Data', 'RDO', 'N. Preco', 'Descricao', 'Unidade', 'Qtd', 'Nucleo', 'Rua/Beco', 'Numero', 'Trecho inicial', 'Trecho final', 'NS', 'Croqui', 'Status', 'Evidencia'],
    ...(sub.memoria ?? []).map((line) => [line.data ?? '', line.rdoId ?? '', line.nPreco, line.descricao, line.unidade, line.qtd, line.nucleo, line.ruaBeco ?? '', line.numero ?? '', line.trechoInicial ?? '', line.trechoFinal ?? '', line.notaServico ?? '', line.croqui ?? '', line.status ?? '', line.evidencia ?? '']),
  ])
  appendSheet(wb, 'DESCONTOS', [
    ['Mes', 'RH', 'Agregados', 'Materiais', 'Materiais + EPI', 'Maquinas', 'Servicos', 'Veiculos', 'Combustivel', 'Abast. Comboio', 'Loc. Equipamentos', 'EPI', 'Total'],
    ...(sub.descontos ?? []).map((row) => [row.mes, row.rh, row.agregados, row.materiaisFerramentas, row.materiaisEpi, row.maquinas, row.servicos, row.veiculos, row.combustivel, row.abastecimentoComboio, row.locEquipamentos, row.epi, row.total]),
  ])
  appendCostSheet(wb, 'RH', sub.rh?.map((row) => ({
    id: row.id,
    mes: row.mes,
    descricao: 'RH consolidado',
    quantidade: row.funcionariosClt + row.funcionariosPj,
    valorUnitario: 1,
    valorTotal: row.total,
  })) ?? [])
  appendCostSheet(wb, 'AGREGADOS', sub.agregados ?? [])
  appendCostSheet(wb, 'MAQUINAS', sub.maquinas ?? [])
  appendCostSheet(wb, 'SERVICOS', sub.servicos ?? [])
  appendCostSheet(wb, 'VEICULOS', sub.veiculos ?? [])
  appendCostSheet(wb, 'COMBUSTIVEL', sub.combustivel ?? [])
  appendCostSheet(wb, 'LOC. EQUIPAMENTOS', sub.locEquipamentos ?? [])
  appendCostSheet(wb, 'EPI', sub.epis ?? [])

  XLSX.writeFile(wb, `medicao-${safeName(sub.nome)}-${safeName(sub.periodo)}.xlsx`)
}

function sameScope(rowContractorId: string | null | undefined, rowNucleo: string | null | undefined, contractorId: string | null, nucleo: string) {
  return (rowContractorId || null) === contractorId && (rowNucleo?.trim() || 'Sem nucleo') === nucleo
}

function normalizeCode(value: string | null | undefined) {
  return String(value ?? '').trim().toUpperCase()
}

function resolvedContractItem(
  line: UnifiedMeasurementMemoryLine,
  contractById: Map<string, UnifiedMeasurementContractItem>,
  contractByNPreco: Map<string, UnifiedMeasurementContractItem>,
) {
  return (line.contract_item_id && contractById.get(line.contract_item_id)) || contractByNPreco.get(normalizeCode(line.n_preco)) || null
}

function resolvedUnitPrice(
  line: UnifiedMeasurementMemoryLine,
  contractById: Map<string, UnifiedMeasurementContractItem>,
  contractByNPreco: Map<string, UnifiedMeasurementContractItem>,
) {
  return num(line.unit_price) || num(resolvedContractItem(line, contractById, contractByNPreco)?.unit_price)
}

function memoryToSubLine(line: UnifiedMeasurementMemoryLine, periodLabel: string): SubempreiteiroMemoriaLinha {
  return {
    id: line.id,
    mes: periodLabel,
    rdoId: line.rdo_id ?? undefined,
    nPreco: line.n_preco ?? '',
    descricao: line.service_description,
    unidade: line.unit ?? '',
    qtd: num(line.quantity),
    nucleo: line.nucleo ?? '',
    ruaBeco: line.street || line.location_text || undefined,
    numero: line.number ?? undefined,
    data: line.created_at?.slice(0, 10),
    trechoInicial: line.trecho_inicial ?? undefined,
    trechoFinal: line.trecho_final ?? undefined,
    notaServico: line.service_order ?? undefined,
    croqui: line.croqui ?? undefined,
    origem: line.rdo_id ? 'RDO Sabesp' : 'Manual',
    status: line.review_status === 'approved' ? 'aprovado' : line.review_status === 'blocked' ? 'bloqueado' : line.review_status === 'rejected' ? 'glosado' : 'em_revisao',
    evidencia: line.evidence_url ?? undefined,
  }
}

function consolidateItems(
  memoryLines: UnifiedMeasurementMemoryLine[],
  contractById: Map<string, UnifiedMeasurementContractItem>,
  contractByNPreco: Map<string, UnifiedMeasurementContractItem>,
  periodLabel: string,
): SubempreteiroItem[] {
  const map = new Map<string, SubempreteiroItem>()
  for (const line of memoryLines) {
    if (line.review_status !== 'approved') continue
    const contract = resolvedContractItem(line, contractById, contractByNPreco)
    const nPreco = line.n_preco || contract?.n_preco || ''
    const key = `${nPreco}|${line.service_description}|${line.unit ?? ''}`
    const current = map.get(key) ?? {
      id: `item-${key}`,
      nPreco,
      nPrecoSabesp: nPreco,
      descricao: contract?.description || line.service_description,
      unidade: line.unit || contract?.unit || '',
      qtd: 0,
      valorUnitario: resolvedUnitPrice(line, contractById, contractByNPreco),
      mes: periodLabel,
      origem: line.rdo_id ? 'RDO Sabesp' : 'Manual',
      rdoId: line.rdo_id ?? undefined,
      contractorId: line.contractor_id ?? null,
      nucleo: line.nucleo ?? undefined,
      retencaoPercentual: contract?.retention_percent ?? 0,
      retencaoObservacao: contract?.retention_rule ?? undefined,
    }
    current.qtd += num(line.quantity)
    if (!current.valorUnitario) current.valorUnitario = resolvedUnitPrice(line, contractById, contractByNPreco)
    map.set(key, current)
  }
  return Array.from(map.values())
}

function buildDescontos(financialEntries: UnifiedMeasurementFinancialEntry[], periodLabel: string): SubempreiteiroDescontoMensal[] {
  const sumType = (type: string) => financialEntries
    .filter((entry) => approvedStatuses.has(entry.status) && entry.entry_type === type)
    .reduce((sum, entry) => sum + Math.abs(num(entry.amount)), 0)
  const row: SubempreiteiroDescontoMensal = {
    id: `desconto-${periodLabel}`,
    mes: periodLabel,
    rh: sumType('rh'),
    agregados: 0,
    materiaisFerramentas: sumType('material'),
    materiaisEpi: 0,
    maquinas: sumType('machine'),
    servicos: sumType('third_party_service'),
    veiculos: sumType('vehicle'),
    combustivel: sumType('fuel'),
    abastecimentoComboio: 0,
    locEquipamentos: 0,
    epi: sumType('epi'),
    total: 0,
    origem: 'Manual',
  }
  row.total = row.rh + row.agregados + row.materiaisFerramentas + row.materiaisEpi + row.maquinas + row.servicos + row.veiculos + row.combustivel + row.abastecimentoComboio + row.locEquipamentos + row.epi
  return [row]
}

function buildOperationalCostTabs(financialEntries: UnifiedMeasurementFinancialEntry[], periodLabel: string) {
  const rowsFor = (type: string): SubempreiteiroCustoLancamento[] => financialEntries
    .filter((entry) => approvedStatuses.has(entry.status) && entry.entry_type === type)
    .map((entry) => ({
      id: entry.id,
      mes: entry.competence || periodLabel,
      data: entry.created_at?.slice(0, 10),
      descricao: entry.description,
      quantidade: 1,
      valorUnitario: Math.abs(num(entry.amount)),
      valorTotal: Math.abs(num(entry.amount)),
      nf: entry.invoice_number ?? undefined,
      origem: 'RDO Sabesp',
      status: 'aprovado',
      nucleo: entry.nucleo ?? undefined,
      evidencia: entry.evidence_url ?? undefined,
    }))
  return {
    agregados: [] as SubempreiteiroCustoLancamento[],
    materiaisFerramentas: rowsFor('material'),
    materiaisEpi: [] as SubempreiteiroCustoLancamento[],
    maquinas: rowsFor('machine'),
    servicos: rowsFor('third_party_service'),
    veiculos: rowsFor('vehicle'),
    combustivel: rowsFor('fuel'),
    abastecimentoComboio: [] as SubempreiteiroCustoLancamento[],
    locEquipamentos: [] as SubempreiteiroCustoLancamento[],
    epis: rowsFor('epi'),
  }
}

function buildNfs(financialEntries: UnifiedMeasurementFinancialEntry[], contractorName: string, periodLabel: string): SubempreiteiroNotaFiscal[] {
  return financialEntries
    .filter((entry) => entry.entry_type === 'invoice')
    .map((entry) => ({
      id: entry.id,
      numero: entry.invoice_number || entry.id.slice(0, 8),
      fornecedor: contractorName,
      observacao: entry.description,
      valorNf: Math.abs(num(entry.amount)),
      valorPago: approvedStatuses.has(entry.status) ? Math.abs(num(entry.amount)) : 0,
      dataEmissao: entry.created_at?.slice(0, 10) ?? '',
      vencimento: '',
      competencia: entry.competence || periodLabel,
      status: entry.status === 'paid' ? 'PAGA' : entry.status === 'approved' ? 'APROVADA' : entry.status === 'glossed' ? 'GLOSADA' : 'PENDENTE',
      dataPagamento: entry.status === 'paid' ? entry.updated_at?.slice(0, 10) ?? '' : '',
      origem: 'Manual',
    }))
}

function buildParametrosFinanceiros(input: {
  periodLabel: string
  grossMeasured: number
  grossApproved: number
  deductions: number
  invoices: number
  netPreview: number
  scopedFinancial: UnifiedMeasurementFinancialEntry[]
}): SubempreiteiroParametroFinanceiro[] {
  const advance = input.scopedFinancial.filter((entry) => approvedStatuses.has(entry.status) && entry.entry_type === 'advance').reduce((sum, entry) => sum + Math.abs(num(entry.amount)), 0)
  const previous = input.scopedFinancial.filter((entry) => approvedStatuses.has(entry.status) && entry.entry_type === 'previous_closing').reduce((sum, entry) => sum + num(entry.amount), 0)
  return [
    { id: `pf-med-${input.periodLabel}`, mes: input.periodLabel, descricao: 'Medicao do periodo', valor: input.grossMeasured, tipo: 'medicao', origem: 'Calculado' },
    { id: `pf-apr-${input.periodLabel}`, mes: input.periodLabel, descricao: 'Medicao aprovada', valor: input.grossApproved, tipo: 'aprovada', origem: 'Calculado' },
    { id: `pf-des-${input.periodLabel}`, mes: input.periodLabel, descricao: 'Descontos aprovados', valor: -input.deductions, tipo: 'desconto', origem: 'Calculado' },
    { id: `pf-adi-${input.periodLabel}`, mes: input.periodLabel, descricao: 'Adiantamento', valor: -advance, tipo: 'adiantamento', origem: 'Calculado' },
    { id: `pf-ant-${input.periodLabel}`, mes: input.periodLabel, descricao: 'Fechamento mes anterior', valor: previous, tipo: 'fechamento', origem: 'Calculado' },
    { id: `pf-nf-${input.periodLabel}`, mes: input.periodLabel, descricao: 'NFs aprovadas/pagas', valor: input.invoices, tipo: 'nf', origem: 'Calculado' },
    { id: `pf-sal-${input.periodLabel}`, mes: input.periodLabel, descricao: 'Valor liquido previsto', valor: input.netPreview, tipo: 'saldo', origem: 'Calculado' },
  ]
}

function hasBlockers(
  sources: UnifiedMeasurementSource[],
  memoryLines: UnifiedMeasurementMemoryLine[],
  financialEntries: UnifiedMeasurementFinancialEntry[],
) {
  return buildExceptions({ sources, memoryLines, financialEntries, grossApproved: 0, netPreview: 0, invoices: 0 }).some((item) => item.severity === 'blocker')
}

function buildExceptions(input: {
  sources: UnifiedMeasurementSource[]
  memoryLines: UnifiedMeasurementMemoryLine[]
  financialEntries: UnifiedMeasurementFinancialEntry[]
  grossApproved: number
  netPreview: number
  invoices: number
}): MeasurementGenerationException[] {
  const exceptions: MeasurementGenerationException[] = []
  for (const source of input.sources) {
    if (!source.contractor_id) exceptions.push({ code: 'source_without_contractor', severity: 'blocker', message: 'Fonte sem subempreiteiro vinculado.', sourceId: source.id })
    if (source.quality_status === 'blocked_by_nc' || source.status === 'blocked') exceptions.push({ code: 'blocked_quality', severity: 'blocker', message: 'Fonte bloqueada pela qualidade.', sourceId: source.id, valueBRL: num(source.amount) })
  }
  for (const line of input.memoryLines) {
    if (!line.n_preco) exceptions.push({ code: 'missing_n_preco', severity: 'blocker', message: 'Memoria sem N. Preco.', sourceId: line.source_id ?? line.id })
    if (num(line.unit_price) <= 0) exceptions.push({ code: 'missing_unit_price', severity: 'blocker', message: 'Memoria sem preco unitario.', sourceId: line.source_id ?? line.id })
  }
  for (const entry of input.financialEntries) {
    if (!approvedStatuses.has(entry.status)) exceptions.push({ code: 'unapproved_financial', severity: entry.entry_type === 'invoice' ? 'warning' : 'blocker', message: 'Lancamento financeiro sem aprovacao.', sourceId: entry.id, valueBRL: Math.abs(num(entry.amount)) })
  }
  if (input.grossApproved > 0 && input.invoices <= 0) {
    exceptions.push({ code: 'missing_invoice', severity: 'warning', message: 'Medicao aprovada sem NF aprovada/paga vinculada.', valueBRL: input.grossApproved })
  }
  if (input.invoices > 0 && Math.abs(input.netPreview - input.invoices) > 1) {
    exceptions.push({ code: 'closing_divergence', severity: 'warning', message: 'Valor liquido previsto diverge das NFs aprovadas/pagas.', valueBRL: Math.abs(input.netPreview - input.invoices) })
  }
  return exceptions
}

function appendSheet(wb: XLSX.WorkBook, name: string, rows: unknown[][]) {
  const ws = XLSX.utils.aoa_to_sheet(rows)
  ws['!cols'] = inferColumns(rows)
  XLSX.utils.book_append_sheet(wb, ws, name.slice(0, 31))
}

function appendCostSheet(wb: XLSX.WorkBook, name: string, rows: SubempreiteiroCustoLancamento[]) {
  appendSheet(wb, name, [
    ['Data', 'Descricao', 'Item', 'Unidade', 'Quantidade', 'Valor unitario', 'Valor total', 'Fornecedor', 'NF', 'Status', 'Evidencia'],
    ...rows.map((row) => [row.data ?? '', row.descricao, row.item ?? '', row.unidade ?? '', row.quantidade, row.valorUnitario, row.valorTotal, row.fornecedor ?? '', row.nf ?? '', row.status ?? '', row.evidencia ?? '']),
  ])
}

function inferColumns(rows: unknown[][]) {
  const width = Math.max(1, ...rows.map((row) => row.length))
  return Array.from({ length: width }, (_, index) => ({
    wch: Math.min(42, Math.max(12, ...rows.map((row) => String(row[index] ?? '').length + 2))),
  }))
}

function safeName(value: string) {
  return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9-]+/gi, '-').replace(/^-+|-+$/g, '').toLowerCase() || 'medicao'
}
